from pathlib import Path
import hashlib,json
from PIL import Image
root=Path('WORKSPACE'); r=root/'extras/der-checkouts/assessment-clarity'; e=root/'extras/der-evidence/assessment-clarity/r1'
items=[('assessment-source.png','source-narrow.png',[16,205,976,636]),('annotation-result.png','result-narrow.png',[16,169,976,676]),('annotation-assessment.png','assessment-narrow.png',[16,174,976,658]),('failed-draft-assessment.png','failed-narrow.png',[16,17,976,590])]
records=[]
for name,raw,rect in items:
 p=r/'docs/images'/name;Image.open(e/raw).crop(rect).save(p)
 records.append(dict(file=name,raw=raw,crop_pixels=rect,size=list(Image.open(p).size),sha256=hashlib.sha256(p.read_bytes()).hexdigest()))
record=dict(application_revision='5efdc2e',captured_on='2026-09-20',browser='Codex in-app browser; dark appearance; native viewport capture',viewport_css=[1000,720],transformation='Pixel crops only; no scaling or content edits',fixture_git_base='86a839341787e986dae6870673efeaf8251a41d0',fixture_sha256=hashlib.sha256((r/'docs/images/create_demo.py').read_bytes()).hexdigest(),images=records,notes='The failed-draft editor was collapsed for this focused view; it opens by default. Full-page captures at the original width were rejected after visual inspection because the browser export duplicated and clipped content. Narrow responsive captures supersede those attempts.')
(r/'docs/images/captures-assessment-clarity.json').write_text(json.dumps(record,indent=2)+'\n',encoding='utf-8')
def replace(path,old,new):
 p=r/path;t=p.read_text(encoding='utf-8');assert old in t,(path,old);p.write_text(t.replace(old,new),encoding='utf-8')
replace('docs/development/annotations.md','1. Read the original comment, code, proposed interpretation and quoted evidence.','1. Read the open source panel, then assess the interpretation using the\n   [field guide](assessment-fields.md). Impact scope describes affected code;\n   investigation needs and missing evidence belong in notes.')
replace('docs/development/annotations.md','The same schema and source-quote checks apply as for model output. Invalid','The current compatible schema and exact source-quote checks apply. Invalid')
replace('docs/development/annotations.md','4. Submit the decision.','4. Add evidence limitations, investigation needs and any additional advice to\n   **Assessment notes and evidence limitations**. Attribute advice beyond the\n   source to yourself; notes are not interpretation text for grouping.\n5. Submit the decision.')
replace('docs/development/annotations.md','5. Open **Annotation progress','6. Open **Annotation progress')
replace('docs/development/failed-drafts.md','Expand **Source for your assessment**.','Read the open **Source for your assessment** panel.')
replace('docs/development/failed-drafts.md','| `scope` | Choose `expression`, `statement`, `function`, `class`, `file`, `module` or `repository`. |','| `scope` | Smallest affected code unit supported by the evidence: `expression`, `statement`, `function`, `class`, `file`, `module`, `repository` or `unknown`. Investigation extent belongs in notes. |')
replace('docs/development/failed-drafts.md','| `exclusions` | Conditions that limit applicability; keep an empty array when none is justified. |','| `exclusions` | Known exceptions or conditions limiting applicability. Keep an empty array when none are identified; put missing evidence in notes. |')
replace('docs/development/failed-drafts.md','The [synthetic demonstration](../images/README.md) is awaiting correction. The\noriginal failed draft is displayed; it has not been replaced by a suggested answer.','The [synthetic demonstration](../images/README.md) is awaiting correction. Its\neditor was collapsed for this image; it opens by default and retains the original\nfailed draft. Read [the assessment field guide](assessment-fields.md) for the\ndistinction between impact, applicability and evidence limitations.')
replace('docs/README.md','| Review and correct interpretations | [Annotations](development/annotations.md) |','| Understand assessment fields | [Field meanings and worked steps](development/assessment-fields.md) |\n| Review and correct interpretations | [Annotations](development/annotations.md) |')
replace('docs/development/README.md','5. Reconcile affected guides','5. Before changing assessment fields or collecting judgements, check the\n   [assessment contract](assessment-contract.md) against prompts, schemas and UI.\n6. Reconcile affected guides')
replace('docs/development/README.md','6. Verify the result','7. Verify the result')
replace('docs/development/study-preparation.md','interpretations and [annotation controls](annotations.md) to record your review.','interpretations and [annotation controls](annotations.md) to record your review.\nUse the [field meanings](assessment-fields.md), distinguish impact from investigation\nneeds, and record any assistance or prior exposure. Pause before saving if a field\ncannot express your judgement faithfully.')
replace('docs/development/assessment-fields.md','## Interpret the fields','![The source comment and code in a distinct, open assessment panel.](../images/assessment-source.png)\n\nThis [synthetic example](../images/README.md) illustrates the source panel; it is\nnot a research judgement.\n\n## Interpret the fields')
p=r/'CONTEXT.md';p.write_text(p.read_text(encoding='utf-8')+'\n## Impact scope\n\nThe smallest affected code unit established by supplied evidence; unknown when\nthat extent cannot be established. Distinct from the area needed for investigation.\n\n## Applicability limits\n\nKnown exceptions or conditions under which a concern or candidate rule does not\napply. Stored as interpretation exclusions; distinct from missing evidence.\n\n## Evidence limitations\n\nFacts the supplied material cannot establish, recorded in annotation notes along\nwith investigation needs. These notes are not interpretation text for grouping.\n',encoding='utf-8')
